{
  "uid" : "4ff339f2b9c56ef1",
  "name" : "test_xfail_expected_failure",
  "fullName" : "Testcases.test_case2.TestCase2#test_xfail_expected_failure",
  "historyId" : "d64559160056d059f07d9cce74305ce8",
  "time" : {
    "start" : 1588672553701,
    "stop" : 1588672553701,
    "duration" : 0
  },
  "description" : "this test is an xfail that will be marked as expected failure",
  "descriptionHtml" : "<p>this test is an xfail that will be marked as expected failure</p>\n",
  "status" : "skipped",
  "statusMessage" : "AssertionError: assert False",
  "statusTrace" : "self = <test_case2.TestCase2 object at 0x000002353F7D3B00>\n\n    @pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure(self):\n        \"\"\"this test is an xfail that will be marked as expected failure\"\"\"\n>       assert False\nE       assert False\n\nTestcases\\test_case2.py:8: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "Testcases"
  }, {
    "name" : "suite",
    "value" : "test_case2"
  }, {
    "name" : "subSuite",
    "value" : "TestCase2"
  }, {
    "name" : "host",
    "value" : "DESKTOP-BKBELAS"
  }, {
    "name" : "thread",
    "value" : "83112-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "Testcases.test_case2"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "4ff339f2b9c56ef1.json",
  "parameterValues" : [ ]
}